Vagrant.configure("2") do |config|
    (1..1).each do |i|
        config.vm.define "master-#{i}" do |master|
            master.vm.box = "bento/ubuntu-24.04"
            master.vm.box_version = "202510.26.0"
            master.vm.hostname = "master-#{i}"
            master.vm.network "private_network", ip: "172.16.0.1#{i}"

            master.ssh.insert_key = false
            master.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
            master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/personal_key.pub"
            master.vm.provision "shell", path: "scripts/common.sh"
            master.vm.provision "shell", path: "scripts/master.sh", env: {"ADVERTISE_IP" => "172.16.0.1#{i}"}

            master.trigger.after :up do |trigger|
              trigger.name = "Update local kubeconfig"
              trigger.run = {path: "scripts/update-local-kubeconfig.sh", args: ["master-#{i}"]}
            end

            master.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.cpus = 2
              vb.memory = "2048"
            end
        end
    end

    (1..2).each do |i|
        config.vm.define "worker-#{i}" do |worker|
            worker.vm.box = "bento/ubuntu-24.04"
            worker.vm.box_version = "202510.26.0"
            worker.vm.hostname = "worker-#{i}"
            worker.vm.network "private_network", ip: "172.16.0.2#{i}"

            worker.ssh.insert_key = false
            worker.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
            worker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/personal_key.pub"
            worker.vm.provision "shell", path: "scripts/common.sh"
            worker.vm.provision "shell", path: "scripts/worker.sh"

            worker.vm.provider "virtualbox" do |vb|
              vb.gui = false
              vb.cpus = 1
              vb.memory = "2048"
            end
        end
    end
end
